/* Illustrative demo attributes, coordinates and photos; not verified visitor information. */
const ACTIVITIES = ['Lernen', 'Entspannen', 'Treffen', 'Warten', 'Spazieren'];
const FEATURES = ['Ruhig', 'Sitzplätze', 'WLAN', 'Steckdose', 'Wetterschutz', 'WC', 'Barrierearm', 'Im Grünen', 'Aussicht'];
const DEMO_POSITION = [47.4245, 9.3767];
const PHOTOS = {
 park: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1000&q=85',
 lake: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=85',
 library: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1000&q=85',
 city: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1000&q=85',
 forest: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1000&q=85'
};
const SEED_PLACES = [
 ['drei','Drei Weieren','Eine kleine Auszeit über der Stadt.','Dreilindenstrasse, St. Gallen',47.4191,9.3909,'lake',['Entspannen','Treffen','Spazieren'],['Im Grünen','Sitzplätze','Aussicht','WC'],'Wasser, Wiesen und ein weiter Blick. Such dir eine Bank am Weg und lass den Alltag für einen Moment hinter dir.'],
 ['stadt','Stadtpark','Grün mitten im Geschehen.','Museumstrasse, St. Gallen',47.4283,9.3812,'park',['Lernen','Entspannen','Treffen'],['Im Grünen','Sitzplätze','Barrierearm','Ruhig'],'Unter alten Bäumen lesen, zusammen eine Pause machen oder einfach die Sonne geniessen. Ein unkomplizierter Treffpunkt in der Stadt.'],
 ['bibliothek','Bibliothek Hauptpost','Platz für deinen nächsten Gedanken.','Gutenbergstrasse 2, St. Gallen',47.4221,9.3698,'library',['Lernen','Warten'],['WLAN','Steckdose','Wetterschutz','Ruhig','Sitzplätze','WC','Barrierearm'],'Helle Arbeitsplätze und Bücher als gute Gesellschaft. Unser Demo-Spot für konzentrierte Lernpausen bei jedem Wetter.'],
 ['kloster','Klosterplatz','Durchatmen in der Altstadt.','Klosterhof, St. Gallen',47.423,9.3779,'city',['Treffen','Warten','Entspannen'],['Sitzplätze','Barrierearm','Aussicht'],'Ein offener Platz mit eindrucksvoller Kulisse. Gut, um sich zu verabreden oder einen Moment zwischen zwei Terminen zu überbrücken.'],
 ['kreuz','Kreuzbleiche','Viel Raum für wenig Plan.','Burgstrasse, St. Gallen',47.4208,9.3595,'park',['Treffen','Entspannen','Spazieren'],['Im Grünen','Sitzplätze','Barrierearm'],'Weite Wiesen, grosse Bäume und genug Platz für eine entspannte Pause mit Freunden.'],
 ['freuden','Freudenberg','Dein Blick über St. Gallen.','Freudenberg, St. Gallen',47.4145,9.385,'lake',['Spazieren','Entspannen'],['Aussicht','Im Grünen','Ruhig','Sitzplätze'],'Ein Weg nach oben, der sich lohnt: ruhige Ecken, Wiesen und ein schöner Perspektivenwechsel.'],
 ['sitter','Sitter am Kubel','Dem Wasser zuhören.','Kubel, St. Gallen',47.4048,9.3268,'forest',['Spazieren','Entspannen'],['Im Grünen','Ruhig'],'Ein naturnaher Ort für eine längere Auszeit. Entlang des Wassers wird die Stadt schnell leiser.'],
 ['roter','Roter Platz','Ein Treffpunkt mit Charakter.','Raiffeisenplatz, St. Gallen',47.4217,9.3735,'city',['Treffen','Warten'],['Sitzplätze','Barrierearm'],'Mitten im Zentrum und leicht wiederzufinden. Ein urbaner Zwischenstopp für spontane Treffen.'],
 ['gallus','Gallusplatz','Altstadt in aller Ruhe.','Gallusplatz, St. Gallen',47.422,9.3774,'city',['Warten','Entspannen'],['Sitzplätze','Ruhig'],'Eine kleine Pause zwischen historischen Fassaden und Altstadtgassen.'],
 ['wild','Wildpark Peter und Paul','Ein Stück Natur am Stadtrand.','Kirchlistrasse, St. Gallen',47.447,9.386,'forest',['Spazieren','Treffen'],['Im Grünen','Aussicht','Sitzplätze','WC'],'Grüne Wege und Ausblicke laden zu einem längeren Spaziergang ein.'],
 ['hsg','HSG – Aussenbereich','Frische Luft zwischen Ideen.','Dufourstrasse 50, St. Gallen',47.4329,9.3759,'park',['Lernen','Treffen'],['Sitzplätze','Aussicht','Im Grünen'],'Eine Pause auf dem Hügel mit Raum für Gedanken und Gespräche.'],
 ['bahnhof','Bahnhofplatz','Kurz warten, gut ankommen.','Bahnhofplatz, St. Gallen',47.4231,9.369,'city',['Warten','Treffen'],['Wetterschutz','Sitzplätze','Barrierearm','WC'],'Ein zentraler Treffpunkt für die Zeit vor der nächsten Verbindung.' ]
].map(([id,name,subtitle,address,lat,lng,photo,activities,features,description])=>({id,name,subtitle,address,lat,lng,photos:[PHOTOS[photo],PHOTOS[photo==='park'?'forest':'park']],activities,features,description,access:'Öffentlich zugänglich · Demoangabe',created:false}));

// Additional regional demo records; positions and amenities remain illustrative.
SEED_PLACES.push(...[["g-bahnhof", "Bahnhofplatz Gossau", "Bahnhofplatz, Gossau SG", 47.4158, 9.2483, "city", ["Warten", "Treffen"], ["Sitzplätze", "Wetterschutz"], "Treffpunkt am Bahnhof für eine Pause vor der Weiterfahrt."], ["g-biblio", "Biblio Gossau", "Säntisstrasse 4a, Gossau SG", 47.4153, 9.2532, "library", ["Lernen", "Warten"], ["Ruhig", "Sitzplätze", "Wetterschutz"], "Bücher und Platz zum Lesen im Happy-Gebäude. Zugang während der Öffnungszeiten; Ausleihe separat."], ["g-andreas", "Platz bei der Andreaskirche", "Kirchplatz, Gossau SG", 47.4161, 9.2517, "city", ["Treffen", "Warten"], ["Sitzplätze"], "Ein zentraler Treffpunkt bei der Andreaskirche."], ["g-moos", "Mooswies", "Mooswiesstrasse, Gossau SG", 47.4105, 9.259, "park", ["Spazieren", "Entspannen"], ["Im Grünen", "Ruhig"], "Eine grüne Umgebung für eine kleine Runde abseits des Zentrums."], ["g-arnegg", "Dorfplatz Arnegg", "Dorfplatz, Arnegg, Gossau SG", 47.442, 9.2513, "city", ["Treffen", "Warten"], ["Sitzplätze"], "Ein Treffpunkt im zu Gossau gehörenden Arnegg."], ["z-linden", "Lindenhof", "Lindenhof, Zürich", 47.373, 8.5409, "city", ["Entspannen", "Treffen"], ["Sitzplätze", "Aussicht"], "Ein Platz über der Altstadt mit Blick Richtung Limmat."], ["z-platz", "Platzspitz", "Platzspitz, Zürich", 47.3822, 8.5407, "park", ["Spazieren", "Entspannen"], ["Im Grünen", "Sitzplätze"], "Parkanlage zwischen Sihl und Limmat nahe dem Hauptbahnhof."], ["z-josef", "Josefwiese", "Josefstrasse, Zürich", 47.3853, 8.5258, "park", ["Treffen", "Entspannen"], ["Im Grünen", "Sitzplätze"], "Eine offene Quartierwiese bei den Viaduktbögen in Zürich-West."], ["z-rieter", "Rieterpark", "Gablerstrasse, Zürich", 47.3585, 8.5305, "forest", ["Spazieren", "Entspannen"], ["Im Grünen", "Ruhig", "Sitzplätze"], "Landschaftspark rund um das Museum Rietberg mit Wiesen und alten Bäumen."], ["z-blatter", "Blatterwiese", "Bellerivestrasse, Zürich", 47.3542, 8.552, "lake", ["Treffen", "Entspannen", "Spazieren"], ["Im Grünen", "Sitzplätze", "Aussicht"], "Wiese am See neben dem Chinagarten für eine Pause am Wasser."]].map(([id,name,address,lat,lng,photo,activities,features,description])=>({id,name,address,lat,lng,activities,features,description,subtitle:'',photos:[PHOTOS[photo],PHOTOS.park],access:'Zugang und Ausstattung vor Ort prüfen · Demoangabe',created:false})));
const REGIONS = {'St. Gallen':[47.4245,9.3767],'Gossau SG':[47.416,9.251],'Zürich':[47.374,8.54]};
